#! /bin/zsh
dat=$(date +'%Y_%m_%d %l_%M_%S%p')
name="screenshot_$dat.png"
voice_path="$HOME/.bin/voice"

function voice(){
  eval "$voice_path '$1'"
  notify-send 'A screenshot' "$1" --icon=dialog-information
}

grim "$HOME/screenshots/$name"

if [ $? -eq 0 ]; then
  notify-send 'Screenshot' "Saved as: $name" --icon=dialog-information
  voice "screenshot saved!"
else
  notify-send 'Screenshot' "failure! $error" --icon=dialog-error
  voice "screenshot failure!"
fi
